### PR TITLE
fix user fetching and layout

### LINKED ISSUE #67: client: user page is breaking since it relies on deprecated RenderMarkdownViewer

### PR DESCRIPTION
**Pull request by EugeneTeu**
close #67 #65

### CODE REVIEW

File: client/pages/forum/index.tsx [hunk 1]
```diff
@@ -117,12 +117,14 @@ const ForumPage = ({ questions, total }): JSX.Element => {
...
-              {record.user.username}
-            </Link>
+            {record.user ? (
+              <Link
+                href={`${Route.USER}/[username]`}
+                as={`${Route.USER}/${record.user.username}`}
+              >
+                {record.user.username}
+              </Link>
+            ) : null}
```
Comment (AaronCQL) [inline client/pages/forum/index.tsx:127]: Is this for the case where the question asker is somehow deleted and thus cannot be found (though it shouldn't happen LOL)? In which case maybe can render something like `<deleted>` to inform the user?

Comment (EugeneTeu) [reply client/pages/forum/index.tsx:127]: yea got some bugs with the link. if its not valid it wont show. So if question no username will have bug

**Review by AaronCQL — APPROVED** [review]
LGTM
